% sf = make_SKP_storageframe('MRIPixelGrid','Sectors','F:\SKP-SC analysis\','06-Transformation\02-ConsolidatedData\',IDtag);
rootpath = 'F:\SKP-SC analysis\';
origdir = pwd;
cd(rootpath);
% save('SKP-sf.mat','sf');
% load SKP_sf.mat
cd(origdir);



view_categories = {'group','subject','slice'};

requested_members.('group') = {'Media','Cells','8wk'};
requested_members.('subject') = {'11','16','18','20','36','39','41','51','54','55','56','58','61','62'};
requested_members.('slice') = {'1EdgeCaudal','2MidCaudal','3Epicentre','4MidCranial','5EdgeCranial'};
requested_members.('segzone') = {'Dorsal','Ventral','Lateral'};

storage_layout = {'group','subject','slice','segzone'};

parx_pairs = {...
    {'MWF','MBP_IntegODThresh'}, ...
    {'MWF','MBP_AreaFraction'}, ...
    {'MWF','EC_IntegODThresh'}, ...
    {'MWF','EC_AreaFraction'}, ...
    {'Dlong','MBP_IntegODThresh'}, ...
    {'Dlong','MBP_AreaFraction'}, ...
    {'Dlong','EC_IntegODThresh'}, ...
    {'Dlong','EC_AreaFraction'}, ...
    {'Dlong','Axon_IntegODThresh'}, ...
    {'Dlong','Axon_AreaFraction'}, ...
    {'Dtrans','MBP_IntegODThresh'}, ...
    {'Dtrans','MBP_AreaFraction'}, ...
    {'Dtrans','EC_IntegODThresh'}, ...
    {'Dtrans','EC_AreaFraction'}, ...
    {'Dtrans','Axon_IntegODThresh'}, ...
    {'Dtrans','Axon_AreaFraction'}, ...
    {'FA','MBP_IntegODThresh'}, ...
    {'FA','MBP_AreaFraction'}, ...
    {'FA','EC_IntegODThresh'}, ...
    {'FA','EC_AreaFraction'}, ...
    {'FA','Axon_IntegODThresh'}, ...
    {'FA','Axon_AreaFraction'}};


n_pairs = length(parx_pairs);
corrcoeff_all = cell(n_pairs,1);

for i_pair=1:n_pairs
    parname_x = parx_pairs{i_pair}{1};
    parname_y = parx_pairs{i_pair}{2};
    vf_x = make_viewframe(parname_x,view_categories,sf,storage_layout,requested_members);
    vf_y = make_viewframe(parname_y,view_categories,sf,storage_layout,requested_members);
    
    [R,R_CI,pval,R_all,R_CI_all,pval_all] = CalcCorrcoeffViewframe(vf_x,vf_y,'Pearson');
end
